
# Ask user to enter the new eye
print("Please enter a character for the eye.")
eye = input()

print("          ################################################################          ")
print("         #                                                                #         ")
print("        #                                                                  #        ")
print("       #                                                                    #       ")
print("#######          "+eye+eye+eye+eye+eye+eye+eye+eye+eye+eye+"                              "+eye+eye+eye+eye+eye+eye+eye+eye+eye+eye+"          #######")
print("#     #                                                                      #     #")
print("#     #                                                                      #     #")
print("#     #                                                                      #     #")
print("#     #                                                                      #     #")
print("#     #                                                                      #     #")
print("#     #                                                                      #     #")
print("#######                                                                      #######")
print("       #                                                                    #       ")
print("        #                                                                  #        ")
print("          ################################################################          ")
print("                    #                                          #                    ")
print("                   #                                            #                   ")
print("                  #                                              #                  ")
print("                 #                                                #                 ")
print("                #                                                  #                ")
print("               #                                                    #               ")
print("              #                                                      #              ")
print("              #                                                      #              ")
print("              #                                                      #              ")
print("              #                                                      #              ")
print("              #                                                      #              ")
print("              #                                                      #              ")
print("              #                                                      #              ")
print("              #                                                      #              ")
print("               #                                                    #               ")
print("                #                                                  #                ")
print("                 #                                                #                 ")
print("                  #                                              #                  ")
print("                   ##############################################                   ")


